### ISSUE TITLE
Use with both connect-mongo & @fastify/helmet causes Error [ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by twrayden** [fastify/session#100]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.2

### Node.js version

16.14.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux Mint 20.2 Cinnamon

### Description

When I use [connect-mongo](https://github.com/jdesboeufs/connect-mongo) as a session store and have [@fastify/helmet](https://github.com/fastify/fastify-helmet) registered, making a request to an endpoint that sets a session value will cause a crash.

- If I remove the session store & keep helmet - it works
- If I remove helmet & keep the session store - it works

I'm not sure if I'm maybe doing something wrong.

Below is the error log:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.writeHead (node:_http_server:308:21)
    at onSendEnd (/home/thomas/repos/fastify-session-repro/node_modules/fastify/lib/reply.js:469:9)
    at wrapOnSendEnd (/home/thomas/repos/fastify-session-repro/node_modules/fastify/lib/reply.js:435:5)
    at next (/home/thomas/repos/fastify-session-repro/node_modules/fastify/lib/hooks.js:213:7)
    at /home/thomas/repos/fastify-session-repro/node_modules/@fastify/session/lib/fastifySession.js:164:7
    at /home/thomas/repos/fastify-session-repro/node_modules/@fastify/session/lib/session.js:135:9
    at /home/thomas/repos/fastify-session-repro/node_modules/connect-mongo/src/lib/MongoStore.ts:399:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### Steps to Reproduce

https://github.com/thomasraydeniscool/fastify-session-repro

### Expected Behavior

Don't crash on send if a session value is set in a request handler.

**Comment by mcollina** [comment]
From a quick look at your code (I did not run it), you should change:

```js
  server.get("/session", async (request, reply) => {
    request.session.hello = "world";

    reply.redirect("/session/test");
    return reply // or remove async from the top
  });

  server.get("/session/test", async (request, reply) => {
    return request.session.hello
  });
```

**Comment by mcollina** [comment]
You didn't update the second route.

**Comment by thomasraydeniscool** [comment]
Legend thanks that fixed it. Is there any documentation about returning reply should I be doing that for all my routes?

**Comment by thomasraydeniscool** [comment]
Found it https://www.fastify.io/docs/latest/Reference/Routes/#async-await

Thanks for your help.

**Comment by WNemencha** [comment]
That helped me solve an issue where my page was sent twice, thanks @mcollina
