### ISSUE TITLE
session.destroy() and saveUninitialized behavior

### ISSUE THREAD

**Issue by yaneony** [fastify/session#106]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian

### Description

When session is being used with option "saveUninitialized = false", while visiting website doesn't create any session cookie. When you for example log in, then session is being initialized and stored in your browser. Then, when you logout and call session.destroy(), session is destroyed, but, new one also initialized. While user basically has no data and don't need any session cookie.

Is it possible to delete session cookie complete instead of replacing one when using "saveUninitialized = false"?

### Steps to Reproduce

-

**Comment by mcollina** [comment]
I don't understand this question. What are you trying to achieve?

**Comment by yaneony** [comment]
Looks like the problem is on my side, so that session cookie is being created even if I set `saveUninitialized: false`.

Just checked that example and everything is working well, so session cookie is destroyed after logout on user side also too.

```JS
/* LIBRARIES
-------------------------------------------------------------- */
import fastify from 'fastify';
import session from '@fastify/session';
import cookie from '@fastify/cookie';

/* APPLICATION
-------------------------------------------------------------- */
const app = fastify({ logger: false });

/* DECORATORS
-------------------------------------------------------------- */
app.register(cookie);
app.register(session, {
  cookieName: 'session',
  secret: '5ethiw4zt73wmzt74wzt745ethiw4zt73wmzt74wzt745ethiw4zt73wmzt74wzt74',
  saveUninitialized: false,
  cookie: {
    secure: false,
    maxAge: 2592000000
  }
});

/* DECORATORS
-------------------------------------------------------------- */
app.get('/', async (req, res) => {
  if (req.session.user) {
    res.type('text/html').send('WELCOME ' + req.session.user + ' | <a href="/logout">LOGOUT</a><br><br>Your Session: <pre>' + JSON.stringify(req.session, true, 2) + '</pre>');
  } else {
    res.type('text/html').send('WELCOME GUEST | <a href="/login">LOGIN</a><br><br>Your Session: <pre>' + JSON.stringify(req.session, true, 2) + '</pre>');
  }
  return res;
});

app.get('/login', async (req, res) => {
  req.session.user = 'FASTIFY';
  res.redirect('/');
  return res;
});

app.get('/logout', async (req, res) => {
  await req.session.destroy();
  res.redirect('/');
  return res;
});

/* STARTUP
-------------------------------------------------------------- */
app.ready(async (err) => {
  if (err) throw err;
  app.listen({ host: '127.0.0.1', port: 3000 });
});
```

**Comment by yaneony** [comment]
Yeah, fastify-flash was on logout, so it created new session.
