### ISSUE TITLE
[docs] Add to "Ecosystem"

### ISSUE THREAD

**Issue by KoichiKiyokawa** [fastify/session#11]
Thank you for maintaining.

## 🚀 Feature Proposal

Add this plugin to https://github.com/fastify/fastify/blob/main/docs/Ecosystem.md

## Motivation

People can easily find this nice repository.

## Example

https://www.fastify.io/ecosystem/

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by zekth** [comment]
https://github.com/fastify/fastify/pull/3239 has been created

**Comment by KoichiKiyokawa** [comment]
@zekth 
Thanks!
