### ISSUE TITLE
Upgrading the `@fastify/cookie` fails to load the plugin

### ISSUE THREAD

**Issue by vorillaz** [fastify/session#111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

6.2.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

Hi there, 
I tried to update all my `fastify` dependencies to the new namespace NPM modules, `@fastify/session` fails to load since it has a dependency on the old named plugin.
https://github.com/fastify/session/blob/master/lib/fastifySession.js#L242-L244

### Steps to Reproduce

Running a simple web server should throw an error:

```js
const fastify = require('fastify');
const fastifySession = require('@fastify/session');
const fastifyCookie = require('@fastify/cookie');

const app = fastify();
app.register(fastifyCookie);
app.register(fastifySession, {secret: 'a secret with minimum length of 32 characters'});
```

### Expected Behavior

Maybe release a major version where `@fastify/cookie` is a dependency or try and add conditional dependencies.

**Comment by climba03003** [comment]
Please update to the `latest` version of `@fastify/session`.
`6.2.0` is pretty old.
