### ISSUE TITLE
`session.save()` does not work on manually decrypted sessions

### ISSUE THREAD

**Issue by shrihari-prakash** [fastify/session#159]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Plugin version

9.0.0

### Node.js version

16.14.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I am trying to have a rolling session. ie, I create a session with a certain timestamp and then try to extend the session expiry inside a socket.io route. The web socket route retrieves the session by using `decryptSession` function of fastify and tries to call `session.touch()` and `session.save()` functions to extend the session at certain points inside the socket APIs and save them to my Redis store.

### Steps to Reproduce

Here's my code for this:

```
app.decryptSession(sid, req, () => {
      if (!req.session?.get('userInfo')?.username) {
        return rejectSocket();
      }
      req.session.touch();
      req.session.save();
      scheduleSessionTouch(socket, req.session);
      return resolve();
    });
```

Looks like the code errors out in the `save()` call with the error `Cannot read properties of undefined (reading 'set')` in the line `lib\session.js:139:39`

Is save() supposed to work on decrypted sessions?

### Expected Behavior

`save()` should store the session to Redis store without errors.

**Comment by Uzlopak** [comment]
This project is currently under heavy development. 

I think we did change something regarding the decrypted Session. So it is possibly already fixed. 

Can you check if it works with the current master?

in package.json change @fastify/session to point to `fastify/session#master` instead of `^9.0.0` and report if the isse still exists?

**Comment by Shrihari-Prakash** [comment]
@Uzlopak , I can confirm that the issue still persists after pointing to master as well.

**Comment by Uzlopak** [comment]
Can you provide a minimal viable code reproduction, so that this can be investigated?

**Comment by Shrihari-Prakash** [comment]
Hello @Uzlopak ,

I've created a minimal viable reproduction code for you here: https://github.com/Shrihari-Prakash/fastify-session-bug

executing `npm install`, `node index.js` and then going to `http://localhost:5000/` should throw you an error on the server side.

**Comment by Shrihari-Prakash** [comment]
@Uzlopak incase you had already downloaded the file, there were some issues with the syntax. Please download it again :)

**Comment by Uzlopak** [comment]
@Shrihari-Prakash 

Well. I created a PR with a potential fix. Please use `fastify/session#fix-159` in you package.json and tell me if it fixes your issue.

Also you have a implementation bug. session.touch does not accept a parameter and session.save() can have an optional callback-parameter. So touchSession has to be like the following

```js
  const touchSession = () => {
    session.touch();
    session.save();
  };
```

**Comment by Shrihari-Prakash** [comment]
Hi @Uzlopak ,
I seem to be getting a different error now.

```
callback is not a function
    at C:\Users\sprakasa\OneDrive - Genesys Telecommunications Laboratories, Inc\Documents\projects\wwe-srv-msteams\node_modules\@fastify\session\lib\session.js:173:9
```

Am I missing something?

**Comment by Shrihari-Prakash** [comment]
Hi @Uzlopak ,
I seem to be getting a different error now.

```
callback is not a function
    at @fastify\session\lib\session.js:173:9
```

Am I missing something?

**Comment by Shrihari-Prakash** [comment]
Ok so it was my bad. You had already mentioned :)

**Comment by Shrihari-Prakash** [comment]
Seems to be working as expected @Uzlopak ! Thanks much for this! 🎉 Do you have any idea when this will be available in public?

**Comment by Uzlopak** [comment]
I hope #161 gets accepted and merged.

**Comment by Shrihari-Prakash** [comment]
Hello @Uzlopak , in PR #161 , I see that you've commented `"It is not documented why decryptSession is deprecated. Only that you once requested to mark it as deprecated."` Can you confirm if this method will be available in future releases? If it will not be, is there an alternative?

**Comment by Uzlopak** [comment]
Well atleast I dont plan to remove it for the next version.

**Comment by Shrihari-Prakash** [comment]
But do you recommend not using it anymore @Uzlopak ? Because I think this functionality is extremely important for hybrid services that has both fastify REST apis and socket.io real time channels and such use cases are very common in my experience.

**Comment by Uzlopak** [comment]
Open an issue and ask why this function got marked as deprecated and what the plans are. Also reassure that this is according to you an important functionality. 

Maybe there is still some convincing needed.

**Comment by Uzlopak** [comment]
@Shrihari-Prakash 

Btw. dont forget to use enableAutoPipelining in ioredis ;)

**Comment by Shrihari-Prakash** [comment]
Oh yes sure thanks for the tip @Uzlopak !🎉
