### ISSUE TITLE
Deprecating `decryptSession` breaks compatibility with web sockets.

### ISSUE THREAD

**Issue by shrihari-prakash** [fastify/session#163]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I see that in recent code changes, the functionality for manually decoding sessions using `decryptSession` is deprecated:
https://github.com/fastify/session/blob/ca0fbe6a7c5fa8ba9ad81616faf08e1bfc47a90e/lib/fastifySession.js#L24

However, this is an important functionality that could potentially render the package completely useless for hybrid services which use Fastify for REST APIs and Socket.IO for web socket end points. Typically, the requests coming to Socket.IO does not pass through Fastify's hooks which means there is no access to sessions inside web sockets at all.

For reference, even Fastify's own `@fastify/websocket` package does not use normal fastify `Request` object.

Is there a reason why this functions is deprecated? In my opinion, use cases where node services offer both REST and Socket APIs are extremely common and this use case should be supported. Or is there an alternative you would be introducing to share sessions between Fastify and other packages like Socket.IO if this is removed in future? This feature is extremely important for my integrations.

**Comment by mcollina** [comment]
What would you recommend we do?

**Comment by Shrihari-Prakash** [comment]
@mcollina is it possible to still retain this function in subsequent versions and not deprecate it if that's possible? Do you see why this should be deprecated in the first place? Does this function raise any security concerns?

**Comment by mcollina** [comment]
Would you mind to send a PR and remove the deprecation notice?

**Comment by Shrihari-Prakash** [comment]
Hi @mcollina , I've raised a PR to reverse the deprecation notice: #164 . Please provide your review.
