### ISSUE TITLE
Session plugin sets an empty SID cookie for a wrong domain

### ISSUE THREAD

**Issue by TheWashiba** [fastify/session#173]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Plugin version

10.0.0

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

I have an interesting case of an extra SID cookie being set for a subdomain.
My Fastify API app is server behind a proxy under a subdomain `api.development.local`, while the session cookie domain is set as `development.local`. 

When I hit a request that saves some state:
```typescript
request.session.user = { id, username, permissions, state: 'authenticated' };
await request.session.save();
```
Any subsequent request will successfully retrieve it by
```typescript
request.session.user
``` 
But after hitting an API with
```typescript
await request.session.destroy();
```
The HTTP request does not clear the SID cookie. Shouldn't it be cleared after it? When I access a session in a subsequent request, it adds an empty cookie, but there's is a problem - different domains:
1. Old SID Cookie with domain `development.local`
2. New empty SID cookie with domain `api.development.local`

Subdomain specific empty cookie now takes precedence and will always be sent to the API server, rendering the session plugin unable to work properly. I believe the issue lies in declared domain not used on clearing the cookie, so the default incoming requests domain is used (with subdomain included).

### Steps to Reproduce

In description.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
