### ISSUE TITLE
request.session type is always any

### ISSUE THREAD

**Issue by FabianFrank** [fastify/session#181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

10.1.0

### Node.js version

18.12.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

Even after adding a type declaration like
```typescript
declare module "fastify" {
    interface Session {
        user: User
    }
}
```
to the code the type of request.session is still `any`.

<img width="407" alt="Screenshot 2022-12-22 at 10 56 22 AM" src="https://user-images.githubusercontent.com/691152/209206847-8a73b9e5-aeb7-4210-a175-1d3bb640e5e3.png">

### Steps to Reproduce

start an empty fastify project, add fastify-session and follow https://github.com/fastify/session#typescript-support

### Expected Behavior

the session type should be applied to request.session

**Comment by Eomm** [comment]
I think you need to extend the `SessionData` - not checked how to do it

**Comment by FabianFrank** [comment]
after applying #182 it seems to work for me: 
<img width="661" alt="Screenshot 2022-12-22 at 12 06 07 PM" src="https://user-images.githubusercontent.com/691152/209217296-38705830-5264-47f6-8356-af640f9b2996.png">

**Comment by kylerush** [comment]
I'm not totally sure I understand what the issue is. This has worked just fine for me. I followed your steps to reproduce and I cannot reproduce the issue. Take a look at this [repo](https://github.com/kylerush/fastify-session-type-check) and let me know if I have something wrong.

<img width="1146" alt="Screenshot 2022-12-26 at 10 55 26 AM" src="https://user-images.githubusercontent.com/150579/209566747-cd70c9ce-b039-4e82-827a-68f0ca6006d5.png">

**Comment by Uzlopak** [comment]
I could also not reproduce the issue.

**Comment by FabianFrank** [comment]
@kylerush thanks to you example I was able to track this down to the `esModuleInterop` typescript setting. If you set it to `false` in your repo the issue starts to reproduce. If you also make sure tsc checks libs (`"skipLibCheck": false`) you can also see the error with tsc:

```
% ./node_modules/.bin/tsc
node_modules/@fastify/session/types/types.d.ts:14:22 - error TS2694: Namespace '"/Users/fabian/tmp/fastify-session-type-check/node_modules/fastify/fastify"' has no exported member 'Session'.

14     session: Fastify.Session;
                        ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:29:60 - error TS2694: Namespace '"/Users/fabian/tmp/fastify-session-type-check/node_modules/fastify/fastify"' has no exported member 'Session'.

29 type CallbackSession = (err: Error | null, result: Fastify.Session) => void;
                                                              ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:86:24 - error TS2694: Namespace '"/Users/fabian/tmp/fastify-session-type-check/node_modules/fastify/fastify"' has no exported member 'Session'.

86       session: Fastify.Session,
                          ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:184:43 - error TS2694: Namespace '"/Users/fabian/tmp/fastify-session-type-check/node_modules/fastify/fastify"' has no exported member 'Session'.

184     constructor(map?: Map<string, Fastify.Session>);
                                              ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:187:24 - error TS2694: Namespace '"/Users/fabian/tmp/fastify-session-type-check/node_modules/fastify/fastify"' has no exported member 'Session'.

187       session: Fastify.Session,
                           ~~~~~~~


Found 5 errors in the same file, starting at: node_modules/@fastify/session/types/types.d.ts:14
```
You should be able to reproduce the issue if you check out my branch https://github.com/kylerush/fastify-session-type-check/pull/1
