### ISSUE TITLE
Fastify-session causing server to send double reply.

### ISSUE THREAD

**Issue by stenlan** [fastify/session#184]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Plugin version

10.1.1

### Node.js version

18.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2

### Description

Double responses are being sent when using fastify-session, and when a session ID is provided, using the prisma-session-store plugin. One of them being undefined, the other being the valid response. Sometimes the former is sent first, sometimes the latter is. This has as a consequence that sometimes a valid response is received by the client, and sometimes an empty one is.

The reason I believe the bug is in fastify-session instead is because as far as I know, the abstraction for the session store should make sure that race conditions are handled correctly by fastify-session.  This bug does not happen when using the default in-memory session store.

### Steps to Reproduce

- Install Fastify, Fastify-session and [https://www.npmjs.com/package/@quixo3/prisma-session-store](prisma-session-store) 3.1.10.
- Configure them in the following way:
```ts
fastify.register(fastifyCookie).register(fastifySession, {
  cookie: {
    secure: false,
    httpOnly: true,
    sameSite: 'lax'
    maxAge: 7 * 24 * 60 * 60 * 1000, // ms
  },
  secret: process.env.COOKIE_SIGNING_SECRET!,
  store: new PrismaSessionStore(prisma, {
    checkPeriod: 5 * 60 * 1000,
    dbRecordIdIsSessionId: true,
    dbRecordIdFunction: undefined,
  }) as SessionStore,
  idGenerator: _request => uuidv4(),
  saveUninitialized: false
});
```
- Add this hook:
```ts
  fastify.addHook('onSend', function (_request, reply, payload, next) { 
    console.log("RESPONSE:" + payload);
    next();
  })
```
- Observe responses being sent twice on any endpoint when a sessionId is provided through the cookie. This is causing a race condition where sometimes a valid response is received on the client, and sometimes not. This happens on Firefox as well as through Postman, and ONLY when a valid session cookie is sent along with the request.

### Expected Behavior

A single reply is sent instead of two replies, one of which is empty.

**Comment by climba03003** [comment]
Can you provide a reproducible code that can be run directly?
It is important to have the code that can run because the reason may not be exist on the snippet of code you provided.

**Comment by ph0t0shop** [comment]
> Can you provide a reproducible code that can be run directly? It is important to have the code that can run because the reason may not be exist on the snippet of code you provided.

Alright, I will try this ASAP. Currently I am very busy but I'll do it when I have time.

**Comment by ph0t0shop** [comment]
It turns out, there is some kind of race condition because I was calling `reply.status(404).send("Response");` and then immediately `return`ing right after. I was NOT awaiting the `.send` call, I did not know it was async. Apparently, sometimes the `return` statement sends a reply before the `.send()` call can, but not always (race condition). It seems that all using fastify-session (maybe any middleware) does is increase the probability of the `.send()` call executing asynchronously.
