### ISSUE TITLE
Don't refresh session on each request

### ISSUE THREAD

**Issue by AaronPorts** [fastify/session#19]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add `rolling` property to force the session identifier cookie to be set on every response as in `express-session`.

### Motivation

[SerayaEryn/fastify-session#126](https://github.com/SerayaEryn/fastify-session/issues/126)
[SerayaEryn/fastify-session#148](https://github.com/SerayaEryn/fastify-session/pull/148)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by AaronPorts** [comment]
Closed by #20
