### ISSUE TITLE
Allow to override FastifyRequest['session']

### ISSUE THREAD

**Issue by gajus** [fastify/session#194]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Allow to override FastifySessionObject or parts of it, e.g. I would like to be able to do this:

```ts
type SessionData = {
  sessionId?: string;
  tikTokOAuthState?: string;
  userAccountAuthenticationTokenId?: AuthenticationToken;
  userAccountId?: number;
};

declare module 'fastify' {
  interface FastifyRequest {
    session: FastifySession<SessionData>;
  }

  interface Session {
    get: <T extends string>(key: T) => SessionData[T];
    set: <T extends string>(key: T, value: SessionData[T]) => void;
  }
}
```

As far as I can see, I am not even able to override `FastifyRequest` `session`.

### Motivation

Have typed `get`, `set`, etc. methods.

**Comment by gajus** [comment]
Regardless, and a separate issue, the current implementation is broken.

```
interface Session {
  foo: number;
}

type Foo = FastifyRequest['session']['foo'];
// gives 'number' (expected)

typeof request.session.get('foo');
// gives 'unknown' (unexpected)
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.m, we use tsd for typescript.

**Comment by gajus** [comment]
We ended up falling back to using https://github.com/mgcrea/fastify-session due to several issues with @fastify/session.

**Comment by mcollina** [comment]
> We ended up falling back to using https://github.com/mgcrea/fastify-session due to several issues with @fastify/session.

I don't see many issues open, also PRs are always welcomed.

FWIW I'm glad fastify-session is back because we forked it due to looking mostly abandoned.

**Comment by gajus** [comment]
You forked https://github.com/SerayaEryn/fastify-session, which has been abandoned for years.

https://github.com/mgcrea/fastify-session is a separate project that has been reasonably well maintained.

After comparing the source codes of both projects, it really feels like forking @mgcrea's project would have been a better place to start from.
