### ISSUE TITLE
Typescript does not compile when using suggested strong typed session

### ISSUE THREAD

**Issue by m1212e** [fastify/session#200]
### Fastify version
4.17.0

### Node.js version
19

### Description

I use this to extend the module:

```
export * from "fastify";

declare module "fastify" {
  interface Session {
    authentication?: {
      userId: string;
      email: string;
    };
  }
}
```

and when I try to compile and run I get:

```
[ERROR] 01:01:42 ⨯ Unable to compile TypeScript:
src/hooks/auth.ts(32,19): error TS2339: Property 'authentication' does not exist on type 'FastifySessionObject'.
```

Why does this happen?

**Comment by Uzlopak** [comment]
Can you provide a repository to investigate further?

**Comment by m1212e** [comment]
Sure: https://github.com/DeutscheModelUnitedNations/munify/tree/ts-build-error-demo
Thanks for investigating!
