### ISSUE TITLE
Redis example outdated

### ISSUE THREAD

**Issue by RichardOestigaard** [fastify/session#202]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.19.2

### Plugin version

10.3.1

### Node.js version

20.3.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Both the example in both examples/redis.js and the benchmark one are outdated.

The client for the RedisStore seems to be undefined.

```
...\node_modules\connect-redis\dist\cjs\index.js:18
        let isRedis = "scanIterator" in client;
                                     ^

TypeError: Cannot use 'in' operator to search for 'scanIterator' in undefined
```

### Steps to Reproduce

```
	const cookiePlugin = require('@fastify/cookie')
	const sessionPlugin = require('@fastify/session')

	
	const redisStoreFactory = require('connect-redis').default
	const Redis = require('ioredis')

	const serv = require('fastify')({
		logger: false,
	});

	const RedisStore = new redisStoreFactory(sessionPlugin);

    const store = new RedisStore({
		client: new Redis({
			enableAutoPipelining: true, // Same issue with and without this.
			port: 6379, // Redis port
			host: "127.0.0.1", // Redis host
		})
	})

	// Session data & cookies
	serv.register(cookiePlugin, {});
	serv.register(sessionPlugin, {
		cookieName: 'sessionId',
		cookie: {
			secure: false,
			httpOnly: false
		},
		store,
		secret: 'TestSecret',
		saveUninitialized: false,
		expires: 48 * 3_600_000 // 48 hours
	});
```

### Expected Behavior

That the example code should work flawlessly
```[tasklist]
### Tasks
```

**Comment by RichardOestigaard** [comment]
The code I provided is adapted, the code from https://github.com/fastify/session/blob/master/examples/redis.js has the same issue aswell with the newest version of both `connect-redis` and `ioredis`.

**Comment by SimenB** [comment]
You need to use the previous version of `connect-redis`
