### ISSUE TITLE
Google phasing out third-party cookies

### ISSUE THREAD

**Issue by nicob-29** [fastify/session#213]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi
Google plans soon to activate phasing out third-party cookies
See Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

Doc about phasing out third-party cookies: https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

This feature request requires the possibility to add "Partitioned" to the cookie like Secure.

### Motivation

Soon activation from Google
Google plans soon to activate phasing out third-party cookies (Search Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline)

### Example

Extend interface CookieOptions to allow the possibility to set Partioned.

I think that request some dependency on https://github.com/jshttp/cookie

**Comment by gurgunday** [comment]
Currently unimplemented in upstream: https://github.com/jshttp/cookie/issues/147

**Comment by mcollina** [comment]
We should fork upstream and add this feature.

**Comment by Uzlopak** [comment]
Am I banned by jshttp or can you also not comment and stuff?

![image](https://github.com/fastify/session/assets/5059100/15cb8f8a-6904-4e70-a9fb-733c10ea9f74)

**Comment by mcollina** [comment]
I could, but really it's better if we fork.

**Comment by gurgunday** [comment]
> Am I banned by jshttp

Weird, I can post comments

> I could, but really it's better if we fork.

I'm down to forking for various reasons, just letting you know that a PR for `Partitioned` is up:

https://github.com/jshttp/cookie/pull/153

**Comment by Uzlopak** [comment]
We had cookie integrated in fastify-cookie and we reverted back to cookie. 

@dougwilson 
Did you ban me from jshttp?

**Comment by dougwilson** [comment]
Why would I ban you? Not really familiar with your name.

**Comment by jsumners** [comment]
That's just a bad GitHub error. It happens to me occasionally on various repos, including Fastify ones. You have to wait and try again later.

**Comment by mcollina** [comment]
@nicob-29 I've opened up https://github.com/fastify/fastify-cookie/pull/260 to move back to use our fork. Would you like to add that feature to fastify-cookie directly?

**Comment by nicob-29** [comment]
Thanks @mcollina
After some effort, https://github.com/jshttp/cookie/pull/153 was merged.
So as you like if you prefer use your fork or not.

**Comment by gurgunday** [comment]
Maybe we can pull that change as well while keeping the fork if there are performance improvements we can do

I have’t gone through its source code yet

**Comment by nicob-29** [comment]
Hi 
Any progress ?

**Comment by gurgunday** [comment]
It’s fixed

Make sure to pass partitioned:true to cookie options

**Comment by nicob-29** [comment]
We use https://www.npmjs.com/package/@fastify/session#cookie to set the cookie information.
Is it possible to upgrade fastify/session to support partitioned too ?

**Comment by gurgunday** [comment]
I see, yeah will do

**Comment by nicob-29** [comment]
@gurgunday 

When do you plan to release this version about partitioned cookie ?

**Comment by gurgunday** [comment]
Just released `10.6.0`

**Comment by gurgunday** [comment]
You're right - seems like I needed to import [CookieSerializeOptions](https://github.com/fastify/fastify-cookie/blob/0c7351cde700f7d213faed6305416131c460407d/types/plugin.d.ts#L137C34-L137C34) and export it back while omitting its [`signed` property](https://github.com/fastify/fastify-cookie/blob/0c7351cde700f7d213faed6305416131c460407d/types/plugin.d.ts#L139)

Or we can just extend `SerializeOptions` again and add `secure`

Super busy right now, so a PR from users would be very welcome

**Comment by nicob-29** [comment]
@gurgunday 
Please take a look to https://github.com/fastify/session/pull/225
