### ISSUE TITLE
Session setter and getter throws ts error inside plugin

### ISSUE THREAD

**Issue by jivan99** [fastify/session#218]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

10.5.0

### Node.js version

18.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

23.1.0

### Description

Using session getter and setter within child context inside a plugin throws ts error stating `Argument of type '"something"' is not assignable to parameter of type '"cookie"'` while it works on root context.

### Steps to Reproduce

```ts
import fastifyCookie from '@fastify/cookie';
import fastifySession from '@fastify/session';
import { fastify, FastifyInstance, FastifyPluginAsync } from 'fastify';

const app: FastifyInstance = fastify({
  logger: { transport: { target: 'pino-pretty' } },
});

app.register(fastifyCookie);

app.register(fastifySession, {
  secret: 'A secret with minimum length of 32 characters is required!',
  cookie: {
    path: '/',
    httpOnly: false,
    secure: false,
    maxAge: 900000,
  },
});

const plugin: FastifyPluginAsync = async (fastify: FastifyInstance) => {
  fastify.get('/', {
    onRequest: [
      async (request) => {
        // throws ts error error
        request.session.set('state', 'abc');
      },
      async () => {},
    ],
    handler: function (request, reply) {
      // throws ts error error
      request.session.get('hello');
      request.session.set('abc', 'def');
      return reply.send('hello');
    },
  });
};

app.register(plugin, { prefix: '/plugin' });

app.get('/', async function (request) {
  // no ts error on root context
  request.session.get<any>('not-exist');
  request.session.set<any>('not-exist', 'happy');
});

const main = async () => {
  try {
    await app.listen({ port: 3000 });
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

main();

```

### Expected Behavior

Using session getter and setter inside plugin should not throw ts error.

**Comment by Eomm** [comment]
I can't see the type augmentation:

https://github.com/fastify/session#typescript-support

PS: typescript does not `throw` - it does not transpile IMHO
I was confused at first read!

**Comment by jivan99** [comment]
My bad, I used `string` instead of `any` and typescript was not happy about it.
```ts
// TS was not with this
request.session.get<string>("nonce")
```
Sorry for the inconvenience. It is working as intended.
