### ISSUE TITLE
isConnectionSecure() is duplicate code from @fastify/cookie/plugin.js

### ISSUE THREAD

**Issue by U-4-E-A** [fastify/session#228]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am currently reworking the session package and noticed that `isConnectionSecure()` is duplicated from `@fastify/cookie/plugin.js`. I want to keep my code D.R.Y. but it is not available as export from the cookie package.

This could be added as an export from the cookie package or a better solution (as this is a test on the Request object) might be to add it as an exported function in the main fastify package. This will centralise the code, avoid W.E.T. and also allow me to delete the function in my own package and simply import it from the main fastify package instead. Thanks.

**Comment by gurgunday** [comment]
Closed by https://github.com/fastify/session/pull/238
