### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by SimenB** [fastify/session#24]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently `SessionStore` (and `request.destroySession`) are callback APIs. Ideally these should be Promise-based instead (or support both if you want to keep that).

Since adaptors (such as `connect-redis`) all expect callback APIs, that API probably has to be kept at least as backing implementation. So dual API (like Fastify itself) probably makes sense.

### Motivation

It's more ergonomic, especially in larger async functions.

### Example

Instead of

```js
await promisify(sessionStore.set.bind(sessionStore))(
  session.sessionId,
  session,
);

//

await promisify(sessionStore.destroy.bind(sessionStore))(session.sessionId);
```

we could do

```js
await sessionStore.set(session.sessionId, session);

//

await sessionStore.destroy(session.sessionId);
```

**Comment by zekth** [comment]
Let's keep both if possible. Would you work on this?

**Comment by SimenB** [comment]
I'm happy to work on this at some point in the future, but I cannot predict at what point I'll have time for it. So if somebody else is up for it that'd be great 🙂
