### ISSUE TITLE
Add the ability to configure cookie options within a route

### ISSUE THREAD

**Issue by ogheo** [fastify/session#257]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Same as https://github.com/fastify/fastify-secure-session?tab=readme-ov-file#configuring-cookie-options-inside-a-route from fastify-secure-session.

### Motivation

In some cases, it might be really useful, like implementing a 'remember me' feature or something else, without big hassles. Continuation of https://github.com/fastify/session/pull/53.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
