### ISSUE TITLE
Bug in memorystore.test.js

### ISSUE THREAD

**Issue by U-4-E-A** [fastify/session#270]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

11.0.1

### Node.js version

22.4.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 Professional

### Description

I am not too familiar with `tap` as a testing package (I use `vitest`) but I believe line 13 is incorrect: -

`store.on('test', () => t.assert.ok(true))`

This would appear to assert that `true` is truthy?

**Comment by Uzlopak** [comment]
If I remember correctly this is equivalent to t.pass of tap. So if you use a plan, the test case will fail if this assertion is not hit

**Comment by climba03003** [comment]
> This would appear to assert that true is truthy?

Yes, it means that the event listener must be called (with the assistance of `t.plan`).
