### ISSUE TITLE
@fastify/session causes typescript error.

### ISSUE THREAD

**Issue by sinbino** [fastify/session#35]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

6.2.1

### Node.js version

16.11.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

alpine 3.14.2

### Description

Importing @fastify/session causes an error in tsc.

### Steps to Reproduce

When importing @fastify/session in ES style, tsc causes an error.

In "index.ts", import the following
``` 
import {FastifyInstance} from 'fastify'
import FastifyCookie   from 'fastify-cookie'
import fastifySession from '@fastify/session'

// other code
```

"tsc index.ts" will cause the following error
```
node_modules/@fastify/session/types/types.d.ts:3:33 - error TS2614: Module '"fastify"' has no exported member 'Session'. Did you mean to use 'import Session from "fastify"' instead?

3 import { FastifyPluginCallback, Session } from "fastify";
```

### Expected Behavior

"tsc index.ts" will exit normally.
This problem does not occur in @fastfiy/session 6.2.0 or earlier.

**Comment by mcollina** [comment]
There was likely some bug introduced.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zekth** [comment]
I confirm it breaks my builds too.

**Comment by climba03003** [comment]
I think we need to revert this https://github.com/fastify/session/pull/32/files

**Comment by climba03003** [comment]
@sinbino Can you help to test against the new version `6.2.2`?

**Comment by sinbino** [comment]
@climba03003

I've upgraded to 6.2.2, but I'm getting more errors...
```
node_modules/@fastify/session/types/types.d.ts:9:22 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

9     session: Fastify.Session;
                       ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:27:45 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

27     set(sessionId: string, session: Fastify.Session, callback: (err?: Error) => void): void;
                                               ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:30:49 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

30       callback: (err?: Error, session?: Fastify.Session) => void
                                                   ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:95:41 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

95   constructor(map?: Map<string, Fastify.Session>);
                                           ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:96:43 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

96   set(sessionId: string, session: Fastify.Session, callback: (err?: Error) => void): void;
                                             ~~~~~~~

node_modules/@fastify/session/types/types.d.ts:97:68 - error TS2694: Namespace '"/srv/app/node_modules/fastify/fastify"' has no exported member 'Session'.

97   get(sessionId: string, callback: (err?: Error, session?: Fastify.Session) => void): void;
                                                                      ~~~~~~~
```
It looks like Fastify.Session is not included in fastify 3.22.1.

I am using the package.json below to get the package.
```
{
  "dependencies": {
    "@fastify/session": "^6.2.1",
    "fastify": "^3.22.1",
    "fastify-cookie": "^5.3.1"
  },
  "devDependencies": {
    "@types/node": "^16.11.6"
  }
}
```
Am I doing something wrong?

**Comment by climba03003** [comment]
Can you provide the `tsconfig.json` you are using?

**Comment by sinbino** [comment]
My tsconfig.json is this.

```
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ESNext",
    "esModuleInterop": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "outDir": "dist",
    "rootDir": ".",
    "baseUrl": "."
  }
}
```

**Comment by climba03003** [comment]
> 
> 
> My tsconfig.json is this.
> 
> ```
> {
>   "compilerOptions": {
>     "module": "CommonJS",
>     "target": "ESNext",
>     "esModuleInterop": true,
>     "noImplicitAny": true,
>     "strictNullChecks": true,
>     "resolveJsonModule": true,
>     "sourceMap": true,
>     "outDir": "dist",
>     "rootDir": ".",
>     "baseUrl": "."
>   }
> }
> ```

I cannot reproduce your error with the `tsconfig.json` given. Can you provide a minimal repro for me to debug?

**Comment by sinbino** [comment]
@climba03003

I created a reproduce repo.
https://github.com/sinbino/issue-fastify-session

**Comment by climba03003** [comment]
> 
> 
> @climba03003
> 
> I created a reproduce repo. https://github.com/sinbino/issue-fastify-session

Sad new is that the import order does matter in TypeScript.
`@fastify/session` must be imported before `fastify`. Otherwise, the `Session` added by `@fastify/session` will conflict the existing types.

**Comment by sinbino** [comment]
@climba03003 
As you pointed out, importing "@fastify/session" before "fastify" solved the error.
I'm new to Typescript, so I didn't realize that.
Thank you for taking the time to help me.

However, I noticed one more problem.
```
// theRedisStore is connect-redis instance (express-session compatible session store)
app.register(fastifySession, {store: theRedisStore, secret: 'theSecret'})
```
Specifying Session Store with code like the above will cause incompatible type errors.
```
Type 'RedisStore' is not assignable to type 'SessionStore'.
```
There seems to be a type incompatibility with session store of express-session.
I've updated reproduce repo https://github.com/sinbino/issue-fastify-session

**Comment by climba03003** [comment]
I am not the consumer of this plugin, let here the voice from others.
If it is too breaking for the usage. I think we need to revert both #32 and #36

@zekth @SimenB WDYT?

**Comment by SimenB** [comment]
`Type 'RedisStore' is not assignable to type 'SessionStore'.` is an old issue, that has never worked with this module

**Comment by sinbino** [comment]
There was no type compatibility error with connect-redis in @fastify/session 6.2.0.
Even after 6.2.1, if store is cast as any, there are no compilation errors and it seems to work correctly.
(I am using it in a project that is more complex than the repro repo.)
I'd really like to use @fastify/session, but is it not recommended to use it in combination with connect-redis?

**Comment by lokshunhung** [comment]
@sinbino I ran into a similar problem like yours, and managed to workaround it by not using `@types/connect-redis` and [declaring the types manually](https://github.com/lokshunhung/issue-fastify-session/blob/3652faf66624153cc9b4b54b0de6c2cf155f5943/app/typedef.d.ts).

It's not ideal and would probably break inside a monorepo where `@types/connect-redis` is somehow pulled in, but it works for my case.

Here's my fork of your repro: https://github.com/lokshunhung/issue-fastify-session

**Comment by sinbino** [comment]
@lokshunhung
Thank you for your advice.
Alternatively, casting the connect-redis object to any worked for me.
These methods work fine, so I will use this method.

The connect-redis object type seems to inherit from the store type of the express-session package, so this problem could be with all express-session compatible stores.
It might be good to have some information about store typecasting in the documentation.
