### ISSUE TITLE
Document typescript issues with some express-session compatible stores

### ISSUE THREAD

**Issue by lokshunhung** [fastify/session#39]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This plugin works with TypeScript, but there are some quirks when using with some express-session compatible store, since their type definitions might be written for express-session in mind. It would be nice to have this documented somewhere.

One example is [connect-redis](https://github.com/tj/connect-redis), where the types [never worked with this module](https://github.com/fastify/session/issues/35#issuecomment-961054163).

Context: from @sinbino in [this issue](https://github.com/fastify/session/issues/35#issuecomment-962768200)
> It might be good to have some information about store typecasting in the documentation.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by lokshunhung** [comment]
@mcollina Sure, here you go: #40
