### ISSUE TITLE
Add a link of this module to the fastify ecosystem page

### ISSUE THREAD

**Issue by mcollina** [fastify/session#48]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.x

### Plugin version

all

### Node.js version

all

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

as titled

### Steps to Reproduce

as titled

**Comment by SimenB** [comment]
https://github.com/fastify/fastify/pull/3239

**Comment by mcollina** [comment]
Good spot!
