### ISSUE TITLE
Missing Typescript documentation.

### ISSUE THREAD

**Issue by vikasg603** [fastify/session#5]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

Typescript documentation is missing from the readme file.
If you are okay, I will try adding a pull request for it, But if you already have some solution with you, try adding it.

### Steps to Reproduce

No

### Expected Behavior

no

**Comment by zekth** [comment]
Go for the PR :)

**Comment by vikasg603** [comment]
Okay, I will try.

**Comment by vikasg603** [comment]
https://github.com/fastify/session/pull/6
