### ISSUE TITLE
Exposing encryptedSessionId leaks secret to database

### ISSUE THREAD

**Issue by cameronmbell** [fastify/session#52]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

6.3.0

### Node.js version

14.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Compared to express session, fastify session exposes the encrypted session id to the database. This could be used to determine the session secret given a database leak and thus leaking temporary password equivalent. It also wastes space by including the sessionId twice and expiry date three times.

express-session
```json
"_id":"abcdefghijklmnopqrstuvwxyz",
"expires":"2022-03-08T09:43:51.997+00:00",
"session":{
    "cookie":{
        "originalMaxAge":"5184000000",
        "expires":"2022-03-08T09:43:35.786+00:00",
        "secure":false,
        "httpOnly":true,
        "domain":null,
        "path":"/",
        "sameSite":null
    }
}
```
fastify/session
```json
"_id":"abcdefghijklmnopqrstuvwxyz",
"expires":"2022-03-08T09:43:51.997+00:00",
"session":{
    "expires":"2022-03-08T09:43:51.997+00:00",
    "cookie":{
        "originalMaxAge":"5184000000",
        "expires":"2022-03-08T09:43:35.786+00:00",
        "secure":false,
        "httpOnly":true,
        "domain":null,
        "path":"/",
        "sameSite":"strict"
    },
    "sessionId":"abcdefghijklmnopqrstuvwxyz",
    "encryptedSessionId":"qwertyuiopasdfghjklzxcvbnm"
}
```

### Steps to Reproduce

```js
import fp from 'fastify-plugin';
import cookie from 'fastify-cookie';
import session from '@fastify/session';

// https://github.com/jdesboeufs/connect-mongo/issues/441
import _ from 'express-session';
import MongoStore from 'connect-mongo';

export default fp(async (fastify, options) => {
    if (!fastify.dbClient) {
        throw new Error('Must register db plugin');
    }

    fastify.register(cookie);
    fastify.register(session, {
        secret: process.env.SECRET,
        saveUninitialized: false,
        cookieName: '__Host-sessionId',
        cookie: {
            sameSite: 'strict',
            httpOnly: true,
            secure: false
        },
        store: MongoStore.create({
            stringify: false,
            client: /* ... */
        })
    });
});
```

### Expected Behavior

Do not write encryptedSessionId to database.

**Comment by climba03003** [comment]
I don't think we can change how `connect-mongo` serialize and deserialize the `session` we passed inside.

https://github.com/jdesboeufs/connect-mongo/blob/master/src/lib/MongoStore.ts#L336-L401

**Comment by mcollina** [comment]
I think we can define `encryptedSessionId` using `defineProperty` and make it non-enumerable.

**Comment by mcollina** [comment]
@cameronmbell 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cameronmbell** [comment]
I'd really rather not, I can try if it's too much work for you, but it'll probably take me 10x the time it'll take you.

**Comment by m0dch3n** [comment]
I was encountering the same issue, so I corrected and committed a solution to my fork:

https://github.com/m0dch3n/session/commit/25dfa84af1424c3cf290632473df5d6ed4c0e391

**Comment by m0dch3n** [comment]
Also see [my comment](https://github.com/m0dch3n/fastify-session/commit/25dfa84af1424c3cf290632473df5d6ed4c0e391#r69274846)

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by m0dch3n** [comment]
done...

**Comment by Uzlopak** [comment]
@rclmenezes 

Here a unit test:

```
'use strict'

const test = require('tap').test
const { buildFastify, DEFAULT_OPTIONS } = require('./util')
const Store = require('../lib/store')

test('should save the session without sessionId and encryptedSessionId', async (t) => {
  t.plan(9)
  const storeMap = new Map()
  const fastify = await buildFastify((request, reply) => {
    request.session.someData = 'some-data'
    t.equal(request.session.someData, 'some-data')

    request.session.save((err) => {
      t.error(err)
      t.equal(storeMap.size, 1)
      const [sessionId, session] = [...storeMap.entries()][0]
      const keys = Object.keys(session)

      console.log(keys)
      t.ok(keys.includes('cookie'))
      t.equal(session.someData, 'some-data')
      t.ok(keys.length, 2)
      t.equal(keys.includes('sessionId'), false)
      t.equal(keys.includes('encryptedSessionId'), false)
    })
    reply.send()
  }, {...DEFAULT_OPTIONS, store: new Store(storeMap)})
  t.teardown(() => fastify.close())

  const response = await fastify.inject({
    url: '/'
  })

  t.equal(response.statusCode, 200)
})

```

**Comment by sarneeh** [comment]
@Uzlopak @rclmenezes Sorry for the offtop but I'm following your work on this folks and just wanted to say a big thank you for your work 🙇 I was already working on this but didn't have enough time to finish it up, your contributions help a lot 🎉
