### ISSUE TITLE
Session does not get destroyed

### ISSUE THREAD

**Issue by Jackzmc** [fastify/session#72]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Plugin version

6.5.0

### Node.js version

16.13.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Version	10.0.19043 Build 19043

### Description

I am attempting to destroy a session, but when I go to verify it has been terminated, it is still active and in the database (I am using `express-mysql-session v2.1.7` to store the sessions).

When I attempted `req.sessionStore.destroy(req.session.sessionId, () => {})`, the same effect had occurred.

### Steps to Reproduce

1. Have a session
2. Attempt to delete it via the sessionStore

This does not work:
```js
req.sessionStore.destroy(sessions[0].session_id, (err: Error) => {
    if(err) throw err
    reply.code(204).send()
})
```

This does:
```js
req.destroySession((err) => {
    if(err) throw err
    reply.code(204).send()
})
```

No errors are thrown, except `FST_ERR_PROMISE_NOT_FULFILLED` related due to the callback style, but still fails if you promisfy it:
```js
function promiseDeleteSession(req: FastifyRequest, sessId: string): Promise<void> {
    return new Promise((resolve, reject) => {
        req.sessionStore.destroy(sessId, (err: Error) => {
            if(err) return reject(err)
            resolve()
        })
    })
    
}
await promiseDeleteSession(req, req.session.sessionId)
``` 
No more errors when using in async, but yet session is still valid.

### Expected Behavior

The session is no longer valid, and it should be removed from the database as well as be invalidated on the server

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Jackzmc** [comment]
I cannot actually reproduce this issue on a test repository, so I'll have to look into what happened, could have been an issue with express-mysql-session for all I know, or some delay in deleting it.
