### ISSUE TITLE
Custom sign/unsign

### ISSUE THREAD

**Issue by simoneromano96** [fastify/session#95]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'd like to be able to specify a custom signing and un-signing function

### Motivation

This is needed to ensure compatibility with a polyglot development environment

### Example

```ts
const Fastify = require('fastify')

type SignFunction = (cookieId: string | Buffer) => string | Buffer
type UnsignFunction = (encryptedCookie: string | Buffer) => string | Buffer

const fastify = Fastify()
fastify.register(fastifySession, { sign: (cookieId: string | Buffer) => mySignFunction(cookieId), unsign: (encryptedCookie: string | Buffer) => myUnsignFunction(cookieId) })
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Uzlopak** [comment]
I merged now the cookie-signature integration PR into fastify-cookie. When it gets released, we can pass the algorithm/signer through to the cookie module

**Comment by mcollina** [comment]
it was released
