### ISSUE TITLE
Race condition (ERR_HTTP_HEADERS_SENT) when migrating to Fastify 4.0.0

### ISSUE THREAD

**Issue by diervo** [fastify/session#99]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Plugin version

9.0.0

### Node.js version

16.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Monterey

### Description

The issue only appears when upgrading to Fastify 4.0.0 and @fastify/session 9.0.0 and only when multiple requests are issued at the same time.

It seems to be a race condition on the save mechanism while the reply has been marked as `sent` already. 
Here is a snippet of the stack trace.

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.writeHead (node:_http_server:309:21)
    at onSendEnd (/app/node_modules/fastify/lib/reply.js:469:9)
    at wrapOnSendEnd (/app/node_modules/fastify/lib/reply.js:435:5)
    at next (/app/node_modules/fastify/lib/hooks.js:213:7)
    at /app/node_modules/@fastify/session/lib/fastifySession.js:164:7
    at app/node_modules/@fastify/session/lib/session.js:135:9
    at tryCatcher (/app/node_modules/standard-as-callback/built/utils.js:12:23)
    at /app/node_modules/standard-as-callback/built/index.js:22:53 {
  code: 'ERR_HTTP_HEADERS_SENT'
  ```

The issue only seems to happen when multiple requests are being sent at the same time, which makes the repro hard.

I understand that not having a real repro might be tricky to pinpoint the issue, but I was hoping that someone might have an idea before I have to debug deeper the whole stack.

### Steps to Reproduce

Given that is a race condition, I was unable to get a small reproducible case. But here is as much detail I could gather:

I have the Redis setup described in the README of this very same repo:

```js
fastify.register(fastifySession, {
        store: new RedisStore({ client: redisClient }),
        secret: sessionSecret,
        cookieName: 'sid',
    });
    
fastify.register(middie);
```

Here is the where the code fails

```
// fastifySession.js
session.save((err) => {
      if (err) {
        done(err)
        return
      }
      // When the exception is thrown reply is already `sent`
      reply.setCookie(
        options.cookieName,
        session.encryptedSessionId,
        session.cookie.options(isConnectionSecure(request))
      )
      done()
```

### Expected Behavior

The server should not crash...

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by diervo** [comment]
Thank @mcollina for the quick response
I knew it that was a stretch to just send the issue without a repro case, but had to try :)

Will send the repro example soon.

**Comment by mcollina** [comment]
Your code as likely a broken promise chain that you now need to tell Fastify how to handle with a `return reply` at the end
of the handler.
